### ISSUE TITLE
Coordinates don't get written into note field

### ISSUE THREAD

**Issue by markggn** [avogadogc/revwherigo#1]
Seems like GS changed something.

revwhereigo: Fetched solution N XXXX revwhereigo.user.js:40:25
revwhereigo: Note already open revwhereigo.user.js:61:17
revwhereigo: Area not open revwhereigo.user.js:70:17
revwhereigo: Saving revwhereigo.user.js:72:13

If I click inside the note field, it works.

**Comment by olivergondza** [comment]
Sorry this was left neglected for so long. The new version moves solution from note to solved coordinates: https://github.com/avogadogc/revwherigo/issues/1.

**Comment by avogadogc** [comment]
Sorry this was left neglected for so long. The new version moves solution from note to solved coordinates field: https://github.com/avogadogc/revwherigo/commit/bb73bd40ab9547fb5955cf7491f1609d1d8f39cb.
